"""Add variant quality and annotations table

Revision ID: 9747879d2156
Revises: 7a22fadc487b
Create Date: 2026-10-07 16:34:01.840122

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9747879d2156"
down_revision: str | Sequence[str] | None = "7a22fadc487b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("gene_name", sa.String(length=255), nullable=False),
        sa.Column("clinical_significance", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["variant_id"], ["variants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("variant_id"),
    )
    op.add_column("variants", sa.Column("quality", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("variants", "quality")
    op.drop_table("annotations")
    # ### end Alembic commands ###
